spring:
  application:
    name=LoadBookingSystem:
    name: load-booking-system

  datasource:
    url: jdbc:postgresql://localhost:5432/load_booking_db
    username: postgres
    password: ${ROOT_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html